### ISSUE TITLE
Bug when using a tilde in destination

### ISSUE THREAD

**Issue by unfokus** [muesli/sync3c#1]
When I use a tilde in the destination to target my home dir it uses the tilde as directory name. In my example the files are getting written to:

`/home/david/go/src/github.com/muesli/sync3c/~/ssd/33c3/`

when the command was

`sync3c -name 33c3 -destination "~/ssd/33c3/"`

**Comment by muesli** [comment]
You need to remove the quotes around the path, so that your shell expands the tilde to your home dir. Anything within the quotes won't be touched by your shell.

I guess I could update the README to point out that the quotes aren't really required by sync3c - then again it behaves exactly like any other cli-app in that regard.
